In [ ]:
# PC 3
# Lorena Belen Cerda Rioja

In [5]:
#link de repositorio, carpeta de archivos
Repo="https://github.com/Lorbe277/Control3_ICDE/raw/main/appendData"

In [170]:
# creando nombre de archivos a lista
level=range(1,5)
files=["level"+str(level)+'.xlsx' for level in level]
files

['level1.xlsx', 'level2.xlsx', 'level3.xlsx', 'level4.xlsx']

In [171]:
# creando link para todos los archivo
alltheLinks=[Repo+"/"+fn for fn in files]
alltheLinks

['https://github.com/Lorbe277/Control3_ICDE/raw/main/appendData/level1.xlsx',
 'https://github.com/Lorbe277/Control3_ICDE/raw/main/appendData/level2.xlsx',
 'https://github.com/Lorbe277/Control3_ICDE/raw/main/appendData/level3.xlsx',
 'https://github.com/Lorbe277/Control3_ICDE/raw/main/appendData/level4.xlsx']

In [268]:
#creando link para cada archivo
file1, file2, file3, file4 = [enlace for enlace in alltheLinks]
file3

'https://github.com/Lorbe277/Control3_ICDE/raw/main/appendData/level3.xlsx'

LIMPIEZA DE DFs

In [273]:
#Importacion de pandas
import pandas as pd
# Obtenci√≥n de la tabla de Excel sin encabezado
data1 = pd.read_excel(file1, header=None)

#diferenciar HDI rank 2021 y 2020
data1.loc[4, 14] = "HDI rank 2020"

data1.head(9)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,Table 1. Human Development Index and its compo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HDI rank,Country,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank 2020,NaN
5,NaN,NaN,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,2021,NaN,2021,NaN,2021,a,2021,a,2021,NaN,2021,b,2020,NaN
7,1,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3,VERY HIGH HUMAN DEVELOPMENT
8,2,Norway,0.961,NaN,83.2339,NaN,18.1852,c,13.00363,NaN,64660.10622,NaN,6,NaN,1,VERY HIGH HUMAN DEVELOPMENT

In [274]:
#seleccionar el encabezado
encabezado=data1.iloc[4]
data1.columns=encabezado
# Eliminar las filas iniciales
data1=data1.drop(index=[0,1,2,3,4,5,6])

# Restablecer el √≠ndice
data1.reset_index(drop=True, inplace=True)

# Mostrar el DataFrame resultante
data1

4,HDI rank,Country,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank 2020,NaN
0,1,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3,VERY HIGH HUMAN DEVELOPMENT
1,2,Norway,0.961,NaN,83.2339,NaN,18.1852,c,13.00363,NaN,64660.10622,NaN,6,NaN,1,VERY HIGH HUMAN DEVELOPMENT
2,3,Iceland,0.959,NaN,82.6782,NaN,19.163059,c,13.76717,NaN,55782.04981,NaN,11,NaN,2,VERY HIGH HUMAN DEVELOPMENT
3,4,"Hong Kong, China (SAR)",0.952,NaN,85.4734,d,17.27817,NaN,12.22621,NaN,62606.8454,NaN,6,NaN,4,VERY HIGH HUMAN DEVELOPMENT
4,5,Australia,0.951,NaN,84.5265,NaN,21.05459,c,12.72682,NaN,49238.43335,NaN,18,NaN,5,VERY HIGH HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,62,Malaysia,0.803,NaN,74.8839,NaN,13.34304,NaN,10.64506,NaN,26657.94355,NaN,-8,NaN,61,VERY HIGH HUMAN DEVELOPMENT
62,63,Georgia,0.802,NaN,71.694,NaN,15.56852,NaN,12.82222,NaN,14664.16825,NaN,17,NaN,64,VERY HIGH HUMAN DEVELOPMENT
63,63,Mauritius,0.802,NaN,73.5552,NaN,15.17353,e,10.42791,e,22025.34631,NaN,-1,NaN,62,VERY HIGH HUMAN DEVELOPMENT
64,63,Serbia,0.802,NaN,74.1923,NaN,14.40009,NaN,11.36987,NaN,19123.02747,NaN,4,NaN,62,VERY HIGH HUMAN DEVELOPMENT
65,66,Thailand,0.8,NaN,78.7154,NaN,15.882219,m,8.69712,NaN,17030.15352,NaN,6,NaN,64,VERY HIGH HUMAN DEVELOPMENT

In [275]:
# Eliminar las primeras 4 filas
data_1= data1.drop(index=[0, 1, 2, 3])

# Restablecer el √≠ndice
data1.reset_index(drop=True, inplace=True)

# Mostrar el DataFrame resultante
data_1

4,HDI rank,Country,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank 2020,NaN
4,5,Australia,0.951,NaN,84.5265,NaN,21.05459,c,12.72682,NaN,49238.43335,NaN,18,NaN,5,VERY HIGH HUMAN DEVELOPMENT
5,6,Denmark,0.948,NaN,81.3753,NaN,18.7148,c,12.96049,NaN,60364.78595,NaN,6,NaN,5,VERY HIGH HUMAN DEVELOPMENT
6,7,Sweden,0.947,NaN,82.9833,NaN,19.41853,c,12.60972,NaN,54489.37401,NaN,9,NaN,9,VERY HIGH HUMAN DEVELOPMENT
7,8,Ireland,0.945,NaN,81.9976,NaN,18.945221,c,11.582223,e,76168.98443,f,-3,NaN,8,VERY HIGH HUMAN DEVELOPMENT
8,9,Germany,0.942,NaN,80.6301,NaN,17.010139,NaN,14.090967,e,54534.21682,NaN,6,NaN,7,VERY HIGH HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,62,Malaysia,0.803,NaN,74.8839,NaN,13.34304,NaN,10.64506,NaN,26657.94355,NaN,-8,NaN,61,VERY HIGH HUMAN DEVELOPMENT
62,63,Georgia,0.802,NaN,71.694,NaN,15.56852,NaN,12.82222,NaN,14664.16825,NaN,17,NaN,64,VERY HIGH HUMAN DEVELOPMENT
63,63,Mauritius,0.802,NaN,73.5552,NaN,15.17353,e,10.42791,e,22025.34631,NaN,-1,NaN,62,VERY HIGH HUMAN DEVELOPMENT
64,63,Serbia,0.802,NaN,74.1923,NaN,14.40009,NaN,11.36987,NaN,19123.02747,NaN,4,NaN,62,VERY HIGH HUMAN DEVELOPMENT
65,66,Thailand,0.8,NaN,78.7154,NaN,15.882219,m,8.69712,NaN,17030.15352,NaN,6,NaN,64,VERY HIGH HUMAN DEVELOPMENT

In [276]:
#Eliminacion de todas las filas que contengan valores NaN
data1_clean= data1[~(data1.iloc[:, 1:].isna().all(axis=1) & data1.iloc[:, 0].notna())]

data1_clean.head()

4,HDI rank,Country,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank 2020,NaN
0,1,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3,VERY HIGH HUMAN DEVELOPMENT
1,2,Norway,0.961,NaN,83.2339,NaN,18.1852,c,13.00363,NaN,64660.10622,NaN,6,NaN,1,VERY HIGH HUMAN DEVELOPMENT
2,3,Iceland,0.959,NaN,82.6782,NaN,19.163059,c,13.76717,NaN,55782.04981,NaN,11,NaN,2,VERY HIGH HUMAN DEVELOPMENT
3,4,"Hong Kong, China (SAR)",0.952,NaN,85.4734,d,17.27817,NaN,12.22621,NaN,62606.8454,NaN,6,NaN,4,VERY HIGH HUMAN DEVELOPMENT
4,5,Australia,0.951,NaN,84.5265,NaN,21.05459,c,12.72682,NaN,49238.43335,NaN,18,NaN,5,VERY HIGH HUMAN DEVELOPMENT

In [313]:
# Eliminaci√≥n de columnas que contienen NaN en la primera fila
data1_clean = data1_clean.loc[:, data1_clean.iloc[0].notna()]


# Reiniciar el √≠ndice del DataFrame
data1_clean.reset_index(drop=True, inplace=True)

# Mostrar el DataFrame resultante
data1_clean.head(5)

4,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank 2020,NaN
0,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3,VERY HIGH HUMAN DEVELOPMENT
1,2,Norway,0.961,83.2339,18.185200,13.00363,64660.10622,6,1,VERY HIGH HUMAN DEVELOPMENT
2,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11,2,VERY HIGH HUMAN DEVELOPMENT
3,4,"Hong Kong, China (SAR)",0.952,85.4734,17.278170,12.22621,62606.84540,6,4,VERY HIGH HUMAN DEVELOPMENT
4,5,Australia,0.951,84.5265,21.054590,12.72682,49238.43335,18,5,VERY HIGH HUMAN DEVELOPMENT

In [314]:
data1_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 10 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   HDI rank                                66 non-null     object
 1   Country                                 66 non-null     object
 2   Human Development Index (HDI)           66 non-null     float64
 3   Life expectancy at birth                66 non-null     float64
 4   Expected years of schooling             66 non-null     float64
 5   Mean years of schooling                 66 non-null     float64
 6   Gross national income (GNI) per capita  66 non-null     float64
 7   GNI per capita rank minus HDI rank      66 non-null     int64
 8   HDI rank 2020                           66 non-null     int64
 9   nan                                     66 non-null     object
dtypes: float64(5), int64(2), object(3)
memory usage: 5.3+ KB

In [310]:
# Convertir las columnas de la 2 a la 7 a n√∫meros
for col in data1_clean.columns[2:8]:
    data1_clean[col] = pd.to_numeric(data1_clean[col], errors='coerce')  # Convertir a float64

# Verificar el resultado
data1_clean

4,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank 2020,NaN
0,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3,VERY HIGH HUMAN DEVELOPMENT
1,2,Norway,0.961,83.2339,18.185200,13.00363,64660.10622,6,1,VERY HIGH HUMAN DEVELOPMENT
2,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11,2,VERY HIGH HUMAN DEVELOPMENT
3,4,"Hong Kong, China (SAR)",0.952,85.4734,17.278170,12.22621,62606.84540,6,4,VERY HIGH HUMAN DEVELOPMENT
4,5,Australia,0.951,84.5265,21.054590,12.72682,49238.43335,18,5,VERY HIGH HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...
61,62,Malaysia,0.803,74.8839,13.343040,10.64506,26657.94355,-8,61,VERY HIGH HUMAN DEVELOPMENT
62,63,Georgia,0.802,71.6940,15.568520,12.82222,14664.16825,17,64,VERY HIGH HUMAN DEVELOPMENT
63,63,Mauritius,0.802,73.5552,15.173530,10.42791,22025.34631,-1,62,VERY HIGH HUMAN DEVELOPMENT
64,63,Serbia,0.802,74.1923,14.400090,11.36987,19123.02747,4,62,VERY HIGH HUMAN DEVELOPMENT
65,66,Thailand,0.800,78.7154,15.882219,8.69712,17030.15352,6,64,VERY HIGH HUMAN DEVELOPMENT

In [311]:
data1_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 10 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   HDI rank                                66 non-null     object
 1   Country                                 66 non-null     object
 2   Human Development Index (HDI)           66 non-null     float64
 3   Life expectancy at birth                66 non-null     float64
 4   Expected years of schooling             66 non-null     float64
 5   Mean years of schooling                 66 non-null     float64
 6   Gross national income (GNI) per capita  66 non-null     float64
 7   GNI per capita rank minus HDI rank      66 non-null     int64
 8   HDI rank 2020                           66 non-null     int64
 9   nan                                     66 non-null     object
dtypes: float64(5), int64(2), object(3)
memory usage: 5.3+ KB

In [312]:
#Limpieza file4
data4 = pd.read_excel(file4, header=None)
encabezado=data4.iloc[0]
data4.columns=encabezado
data4 = data4.drop(index=0)
data4.reset_index(drop=True, inplace=True)


data4.head(7)

,HDI rank,Country,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,le
0,160,Tanzania (United Republic of),LOW HUMAN DEVELOPMENT,0.549,66.2007,9.22149,6.372899,2664.329096,7,NaN
1,161,Pakistan,LOW HUMAN DEVELOPMENT,0.544,66.0979,8.65835,4.53633,4623.70543,-19,NaN
2,162,Togo,LOW HUMAN DEVELOPMENT,0.539,61.6194,12.950494,5.016807,2166.619062,12,NaN
3,163,Haiti,LOW HUMAN DEVELOPMENT,0.535,63.1924,9.7,5.554,2847.500746,2,NaN
4,163,Nigeria,LOW HUMAN DEVELOPMENT,0.535,52.676,10.127584,7.181074,4790.284425,-22,NaN
5,165,Rwanda,LOW HUMAN DEVELOPMENT,0.534,66.0722,11.23097,4.425292,2209.795202,6,NaN
6,166,Benin,LOW HUMAN DEVELOPMENT,0.525,59.821,10.76668,4.304786,3408.965923,-7,NaN

In [282]:
data4_clean= data4[~(data4.iloc[:, 2:].isna().all(axis=1) & data4.iloc[:, 1].notna())]  #eliminar filas con NaN
data4_clean = data4_clean.loc[:, data4_clean.iloc[0].notna()]   #eliminar columna con NaN
data4_clean.reset_index(drop=True, inplace=True)
data4_clean.head()

,HDI rank,Country,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,160,Tanzania (United Republic of),LOW HUMAN DEVELOPMENT,0.549,66.2007,9.22149,6.372899,2664.329096,7
1,161,Pakistan,LOW HUMAN DEVELOPMENT,0.544,66.0979,8.65835,4.53633,4623.70543,-19
2,162,Togo,LOW HUMAN DEVELOPMENT,0.539,61.6194,12.950494,5.016807,2166.619062,12
3,163,Haiti,LOW HUMAN DEVELOPMENT,0.535,63.1924,9.7,5.554,2847.500746,2
4,163,Nigeria,LOW HUMAN DEVELOPMENT,0.535,52.676,10.127584,7.181074,4790.284425,-22

In [283]:
for col in data4_clean.columns[3:9]:
    data4_clean[col] = pd.to_numeric(data4_clean[col], errors='coerce')
data4_clean.head()
data4_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 9 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   HDI rank                                32 non-null     object
 1   Country                                 32 non-null     object
 2   nan                                     32 non-null     object
 3   Human Development Index (HDI)           32 non-null     float64
 4   Life expectancy at birth                32 non-null     float64
 5   Expected years of schooling             32 non-null     float64
 6   Mean years of schooling                 32 non-null     float64
 7   Gross national income (GNI) per capita  32 non-null     float64
 8   GNI per capita rank minus HDI rank      32 non-null     int64
dtypes: float64(5), int64(1), object(3)
memory usage: 2.4+ KB

In [291]:
#limpieza file2
data2 = pd.read_excel(file2, header=None)
data2.loc[0, 11] = "HDI rank 2020"
encabezado=data2.iloc[0]
data2.columns=encabezado

data2= data2.drop(index=[0, 1, 2])
data2.reset_index(drop=True, inplace=True)

data2_clean= data2[~(data2.iloc[:, 1:].isna().all(axis=1) & data2.iloc[:, 0].notna())]  #eliminar filas con NaN
data2_clean = data2_clean.loc[:, data2_clean.iloc[0].notna()]   #eliminar columna con NaN
data2_clean = data2_clean.drop(columns=data2.columns[6])   #tiene valores adicionales al NaN
data2_clean.reset_index(drop=True, inplace=True)

for col in data2_clean.columns[2:8]:
    data2_clean[col] = pd.to_numeric(data2_clean[col], errors='coerce')

data2_clean.head()

data2_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 9 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   HDI rank                                49 non-null     object
 1   Country                                 49 non-null     object
 2   Human Development Index (HDI)           49 non-null     float64
 3   Life expectancy at birth                49 non-null     float64
 4   Expected years of schooling             49 non-null     float64
 5   Mean years of schooling                 49 non-null     float64
 6   Gross national income (GNI) per capita  49 non-null     float64
 7   GNI per capita rank minus HDI rank      49 non-null     int64
 8   HDI rank 2020                           49 non-null     object
dtypes: float64(5), int64(1), object(3)
memory usage: 3.6+ KB

In [304]:
# limpieza file 3
data3 = pd.read_excel(file3, header=None)
data3.loc[0, 14] = "HDI rank 2020"
encabezado=data3.iloc[0]
data3.columns=encabezado

data3= data3.drop(index=[0, 1, 2])
data3.reset_index(drop=True, inplace=True)

data3_clean= data3[~(data3.iloc[:, 1:].isna().all(axis=1) & data3.iloc[:, 0].notna())]  #eliminar filas con NaN
data3_clean = data3_clean.loc[:, data3_clean.iloc[0].notna()]   #eliminar columna con NaN
data3_clean.reset_index(drop=True, inplace=True)

for col in data3_clean.columns[2:9]:
    data3_clean[col] = pd.to_numeric(data3_clean[col], errors='coerce')



#data3_clean = data3_clean.drop(columns=data3.columns[8])

data3_clean.head()

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank 2020
0,116,Philippines,0.699,69.2664,13.126570,8.969100,8920.428468,-3,113
1,117,Botswana,0.693,61.1409,12.265138,10.340000,16198.318410,-43,110
2,118,Bolivia (Plurinational State of),0.692,63.6304,14.946971,9.827750,8111.190194,0,119
3,118,Kyrgyzstan,0.692,69.9774,13.195300,11.374106,4566.303831,26,121
4,120,Venezuela (Bolivarian Republic of),0.691,70.5536,12.816080,11.107277,4810.882621,20,118

In [305]:
data3_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 9 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   HDI rank                                44 non-null     object
 1   Country                                 44 non-null     object
 2   Human Development Index (HDI)           44 non-null     float64
 3   Life expectancy at birth                44 non-null     float64
 4   Expected years of schooling             44 non-null     float64
 5   Mean years of schooling                 44 non-null     float64
 6   Gross national income (GNI) per capita  44 non-null     float64
 7   GNI per capita rank minus HDI rank      44 non-null     int64
 8   HDI rank 2020                           44 non-null     int64
dtypes: float64(5), int64(2), object(2)
memory usage: 3.2+ KB

INTEGRACI√ìN DE DFs

In [297]:
# creaci√≥n de lista de los 4 data frames
import pandas as pd

DFs=[data1_clean,data2_clean,data3_clean,data4_clean]

In [298]:
# guardando los nombres de las columnas
allColumnNames=[]
for df in DFs:
    allColumnNames.append(set(df.columns))

# verificando si tienen la misma cantidad
[len(cols) for cols in allColumnNames]

[10, 9, 9, 9]

In [299]:
# detalle de columnas en com√∫n
commonColumns=set.intersection(*allColumnNames)
len(commonColumns),commonColumns

(8,
 {'Country',
  'Expected years of schooling',
  'GNI per capita rank minus HDI rank',
  'Gross national income (GNI) per capita',
  'HDI rank',
  'Human Development Index (HDI) ',
  'Life expectancy at birth',
  'Mean years of schooling'})

In [300]:
# columna diferente
set.union(*allColumnNames)-commonColumns

{'HDI rank 2020', nan}

In [301]:
#eliminar esa columna
allDFs_sameNames=[df.loc[:,list(commonColumns)] for df in DFs]
len(allDFs_sameNames)

4

In [302]:
#concatenar
#allDFs_sameNames=[df.loc[:,list(commonColumns)] for df in DFs]
allDFsConcat = pd.concat(allDFs_sameNames, ignore_index=True)
allDFsConcat

,Gross national income (GNI) per capita,Human Development Index (HDI),Expected years of schooling,GNI per capita rank minus HDI rank,Life expectancy at birth,Country,HDI rank,Mean years of schooling
0,66933.004540,0.962,16.500299,5,83.9872,Switzerland,1,13.859660
1,64660.106220,0.961,18.185200,6,83.2339,Norway,2,13.003630
2,55782.049810,0.959,19.163059,11,82.6782,Iceland,3,13.767170
3,62606.845400,0.952,17.278170,6,85.4734,"Hong Kong, China (SAR)",4,12.226210
4,49238.433350,0.951,21.054590,18,84.5265,Australia,5,12.726820
...,...,...,...,...,...,...,...,...
186,731.786709,0.426,10.722722,4,61.6627,Burundi,187,3.129267
187,966.058611,0.404,8.040172,1,53.8947,Central African Republic,188,4.334000
188,1239.866936,0.400,6.957112,-3,61.5763,Niger,189,2.116717
189,1364.169417,0.394,8.035914,-7,52.5254,Chad,190,2.573774
190,767.787000,0.385,5.542510,-1,54.9752,South Sudan,191,5.726140

In [303]:
allDFsConcat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Gross national income (GNI) per capita  191 non-null    float64
 1   Human Development Index (HDI)           191 non-null    float64
 2   Expected years of schooling             191 non-null    float64
 3   GNI per capita rank minus HDI rank      191 non-null    int64
 4   Life expectancy at birth                191 non-null    float64
 5   Country                                 191 non-null    object
 6   HDI rank                                191 non-null    object
 7   Mean years of schooling                 191 non-null    float64
dtypes: float64(5), int64(1), object(2)
memory usage: 12.1+ KB

In [326]:
#limpieza de nombres de paises
# ubicar paises con nombres varios
allDFsConcat['Country'] = allDFsConcat['Country'].str.replace(r'\([^)]*\)', '', regex=True)
allDFsConcat['Country'] = allDFsConcat['Country'].str.split(',').str[0]
allDFsConcat['Country'] = allDFsConcat['Country'].str.upper()
allDFsConcat.head(5)

,Gross national income (GNI) per capita,Human Development Index (HDI),Expected years of schooling,GNI per capita rank minus HDI rank,Life expectancy at birth,Country,HDI rank,Mean years of schooling
0,66933.00454,0.962,16.500299,5,83.9872,SWITZERLAND,1,13.85966
1,64660.10622,0.961,18.185200,6,83.2339,NORWAY,2,13.00363
2,55782.04981,0.959,19.163059,11,82.6782,ICELAND,3,13.76717
3,62606.84540,0.952,17.278170,6,85.4734,HONG KONG,4,12.22621
4,49238.43335,0.951,21.054590,18,84.5265,AUSTRALIA,5,12.72682

MERGING

In [319]:
link1="https://github.com/Lorbe277/Control3_ICDE/raw/main/countryCODES.xlsx"

import pandas as pd
# Tabla CountryCODES
country=pd.read_excel(link1, header=None)
country

,0,1,2,3,4
0,Country,Officialstatename,InternetccTLD,iso2,iso3
1,AFGHANISTAN,The Islamic Republic of Afghanistan,.af,AF,AFG
2,ALBANIA,The Republic of Albania,.al,AL,ALB
3,ALGERIA,The People's Democratic Republic of Algeria,.dz,DZ,DZA
4,ANGOLA,The Republic of Angola,.ao,AO,AGO
...,...,...,...,...,...
167,UZBEKISTAN,The Republic of Uzbekistan,.uz,UZ,UZB
168,VIET NAM,The Socialist Republic of Viet Nam,.vn,VN,VNM
169,YEMEN,The Republic of Yemen,.ye,YE,YEM
170,ZAMBIA,The Republic of Zambia,.zm,ZM,ZMB
171,ZIMBABWE,The Republic of Zimbabwe,.zw,ZW,ZWE

In [328]:
encabezado1=country.iloc[0]
country.columns=encabezado1
country

,Country,Officialstatename,InternetccTLD,iso2,iso3
0,Country,Officialstatename,InternetccTLD,iso2,iso3
1,AFGHANISTAN,The Islamic Republic of Afghanistan,.af,AF,AFG
2,ALBANIA,The Republic of Albania,.al,AL,ALB
3,ALGERIA,The People's Democratic Republic of Algeria,.dz,DZ,DZA
4,ANGOLA,The Republic of Angola,.ao,AO,AGO
...,...,...,...,...,...
167,UZBEKISTAN,The Republic of Uzbekistan,.uz,UZ,UZB
168,VIET NAM,The Socialist Republic of Viet Nam,.vn,VN,VNM
169,YEMEN,The Republic of Yemen,.ye,YE,YEM
170,ZAMBIA,The Republic of Zambia,.zm,ZM,ZMB
171,ZIMBABWE,The Republic of Zimbabwe,.zw,ZW,ZWE

In [329]:
# merge de ambas DFs
merge=allDFsConcat.merge(country,left_on='Country',right_on='Country')
merge

,Gross national income (GNI) per capita,Human Development Index (HDI),Expected years of schooling,GNI per capita rank minus HDI rank,Life expectancy at birth,Country,HDI rank,Mean years of schooling,Officialstatename,InternetccTLD,iso2,iso3
0,66933.004540,0.962,16.500299,5,83.9872,SWITZERLAND,1,13.859660,The Swiss Confederation,.ch,CH,CHE
1,64660.106220,0.961,18.185200,6,83.2339,NORWAY,2,13.003630,The Kingdom of Norway,.no,NO,NOR
2,55782.049810,0.959,19.163059,11,82.6782,ICELAND,3,13.767170,Iceland,.is,IS,ISL
3,49238.433350,0.951,21.054590,18,84.5265,AUSTRALIA,5,12.726820,The Commonwealth of Australia,.au,AU,AUS
4,60364.785950,0.948,18.714800,6,81.3753,DENMARK,6,12.960490,The Kingdom of Denmark,.dk,DK,DNK
...,...,...,...,...,...,...,...,...,...,...,...,...
141,1198.073924,0.446,10.219152,2,59.3247,MOZAMBIQUE,185,3.197642,The Republic of Mozambique,.mz,MZ,MOZ
142,2132.629443,0.428,7.423038,-11,58.9414,MALI,186,2.310000,The Republic of Mali,.ml,ML,MLI
143,731.786709,0.426,10.722722,4,61.6627,BURUNDI,187,3.129267,The Republic of Burundi,.bi,BI,BDI
144,1364.169417,0.394,8.035914,-7,52.5254,CHAD,190,2.573774,The Republic of Chad,.td,TD,TCD
145,767.787000,0.385,5.542510,-1,54.9752,SOUTH SUDAN,191,5.726140,The Republic of South Sudan,.ss,SS,SSD

FALLECIDOS COVID

In [339]:
link2="https://github.com/Lorbe277/Control3_ICDE/raw/main/fallecidosCOVID.csv"

fallecidosC=pd.read_csv(link2)
fallecidosC

       FECHA_CORTE;FECHA_FALLECIMIENTO;EDAD_DECLARADA;SEXO;CLASIFICACION_DEF;DEPARTAMENTO;PROVINCIA;DISTRITO;UBIGEO;UUID
0       20240317;20220219;63;MASCULINO;Criterio virol√≥...
1       20240317;20210529;74;MASCULINO;Criterio virol√≥...
2       20240317;20210623;72;FEMENINO;Criterio SINADEF...
3       20240317;20210824;85;MASCULINO;Criterio invest...
4       20240317;20210627;46;MASCULINO;Criterio virol√≥...
...                                                   ...
220913  20240317;20200809;77;MASCULINO;Criterio radiol...
220914  20240317;20201028;81;MASCULINO;Criterio cl√≠nic...
220915  20240317;20200515;68;FEMENINO;Criterio SINADEF...
220916  20240317;20210414;66;FEMENINO;Criterio cl√≠nico...
220917  20240317;20200819;61;MASCULINO;Criterio nexo e...

[220918 rows x 1 columns]

In [334]:
fallecidosC.shape

(220918, 1)